Import("env")
import os

project_dir = env.subst("$PROJECT_DIR")
html_path = os.path.join(project_dir, "src", "web", "index.html")
css_path  = os.path.join(project_dir, "src", "web", "style.css")
out_path  = os.path.join(project_dir, "include", "string_constants.h")

with open(html_path, "r") as f:
    html = f.read()
with open(css_path, "r") as f:
    css = f.read()

with open(out_path, "w") as f:
    f.write("// Auto-generated by tools/generate_strings.py — do not edit directly\n")
    f.write("// Edit src/web/index.html and src/web/style.css instead\n\n")
    f.write('const char index_html[] PROGMEM = /* html */ R"rawliteral(\n')
    f.write(html)
    f.write('\n)rawliteral";\n\n')
    f.write('const char CSS_CODE[] PROGMEM = /* css */ R"rawliteral(\n')
    f.write(css)
    f.write('\n)rawliteral";\n')

print("Generated include/string_constants.h from src/web/")
